include:
  - project: 'sebsoft/open-source/gitlab'
    ref: main
    file: '/opensource-plugin/opensource-plugin-405+.yml'

variables:
  PLUGIN: "local_wisa"
  PATHNAME: "local/wisa"
  REPOURL: "https://github.com/Lesterhuis-Training-en-Consultancy/local_wisa"
  REPOSYS: "git"
  IGNORE_CAMP: "true"
