<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Moodle Events API helper for high-level local_wisa audit events.
 *
 * @package    local_wisa
 * @copyright  2026 Sebsoft.nl <helpdesk@sebsoft.nl>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace local_wisa;

/**
 * Triggers high-level Moodle events without exposing SIS/API diagnostics.
 *
 * @package    local_wisa
 * @copyright  2026 Sebsoft.nl <helpdesk@sebsoft.nl>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class event_logger {
    /** Allowed scalar keys for Moodle event metadata. */
    private const SAFE_KEYS = [
        'source',
        'mode',
        'forcefull',
        'status',
        'reason',
        'duration_seconds',
        'duration_ms',
        'courses_created',
        'courses_updated',
        'courses_failed',
        'courses_skipped',
        'users_created',
        'users_updated',
        'users_failed',
        'enrolments_created',
        'enrolments_updated',
        'enrolments_warned',
        'enrolments_failed',
        'enrolments_skipped',
        'unenrolments_completed',
        'unenrolments_warned',
        'unenrolments_failed',
        'unenrolments_skipped',
        'summary',
        'courses_found',
        'users_found',
        'count',
        'component',
        'stream',
        'phase',
        'transport',
        'outcome',
        'rowcount',
        'errorcode',
    ];

    /**
     * Trigger one high-level admin action event.
     *
     * @param string $eventclass Fully-qualified Moodle event class name.
     * @param array $other Candidate event metadata.
     * @return void
     */
    public static function admin_action(string $eventclass, array $other): void {
        self::trigger_event($eventclass, $other);
    }

    /**
     * Trigger sync started event.
     *
     * @param string $source Active SIS source.
     * @param string $mode Sync mode.
     * @param bool $forcefull Whether this is a forced full sync.
     * @return void
     */
    public static function sync_started(string $source, string $mode, bool $forcefull): void {
        self::trigger_event(\local_wisa\event\sync_started::class, [
            'source' => $source,
            'mode' => $mode,
            'forcefull' => $forcefull,
        ]);
    }

    /**
     * Trigger sync skipped event.
     *
     * @param string $source Active SIS source.
     * @param string $reason Machine-readable skip reason.
     * @return void
     */
    public static function sync_skipped(string $source, string $reason): void {
        self::trigger_event(\local_wisa\event\sync_skipped::class, [
            'source' => $source,
            'reason' => $reason,
            'status' => 'skipped',
        ]);
    }

    /**
     * Trigger sync failed event.
     *
     * @param string $source Active SIS source.
     * @param string $mode Sync mode.
     * @param bool $forcefull Whether this is a forced full sync.
     * @param int $duration Duration in seconds.
     * @return void
     */
    public static function sync_failed(string $source, string $mode, bool $forcefull, int $duration): void {
        self::trigger_event(\local_wisa\event\sync_failed::class, [
            'source' => $source,
            'mode' => $mode,
            'forcefull' => $forcefull,
            'status' => 'failed',
            'duration_seconds' => $duration,
        ]);
    }

    /**
     * Trigger sync completed event.
     *
     * @param string $source Active SIS source.
     * @param string $mode Sync mode.
     * @param bool $forcefull Whether this is a forced full sync.
     * @param int $duration Duration in seconds.
     * @param string $summary High-level summary generated by sync_manager.
     * @param sync_stats $stats Runtime sync counters.
     * @param string $status Aggregate run status.
     * @return void
     */
    public static function sync_completed(
        string $source,
        string $mode,
        bool $forcefull,
        int $duration,
        string $summary,
        sync_stats $stats,
        string $status = 'success'
    ): void {
        self::trigger_event(\local_wisa\event\sync_completed::class, [
            'source' => $source,
            'mode' => $mode,
            'forcefull' => $forcefull,
            'status' => $status,
            'duration_seconds' => $duration,
            'courses_created' => $stats->coursecreate,
            'courses_updated' => $stats->courseupdate,
            'courses_failed' => $stats->coursefail,
            'courses_skipped' => $stats->courseskip,
            'users_created' => $stats->usercreate,
            'users_updated' => $stats->userupdate,
            'users_failed' => $stats->userfail,
            'enrolments_created' => $stats->enrolcreate,
            'enrolments_updated' => $stats->enrolupdate,
            'enrolments_warned' => $stats->enrolwarn,
            'enrolments_failed' => $stats->enrolfail,
            'enrolments_skipped' => $stats->enrolskip,
            'unenrolments_completed' => $stats->unenrolok,
            'unenrolments_warned' => $stats->unenrolwarn,
            'unenrolments_failed' => $stats->unenrolfail,
            'unenrolments_skipped' => $stats->unenrolskip,
            'summary' => $summary,
        ]);
    }

    /**
     * Return the configured active SIS source name.
     *
     * @return string
     */
    public static function active_source(): string {
        $source = get_config('local_wisa', 'active_source');
        return is_string($source) && trim($source) !== '' ? $source : 'wisa';
    }

    /**
     * Return current sync mode label.
     *
     * @param bool|null $dryrun Explicit dry-run override.
     * @return string
     */
    public static function mode_label(?bool $dryrun = null): string {
        if ($dryrun === null) {
            $dryrun = (bool)get_config('local_wisa', 'dry_run');
        }
        return $dryrun ? 'DRY-RUN' : 'LIVE';
    }

    /**
     * Trigger a Moodle event with sanitised scalar metadata.
     *
     * @param string $eventclass Fully-qualified event class name.
     * @param array $other Candidate event metadata.
     * @return void
     */
    private static function trigger_event(string $eventclass, array $other): void {
        if (!is_subclass_of($eventclass, \core\event\base::class)) {
            throw new \coding_exception('Invalid Moodle event class: ' . $eventclass);
        }
        $eventclass::create([
            'context' => \context_system::instance(),
            'other' => self::safe_other($other),
        ])->trigger();
    }

    /**
     * Keep only whitelisted scalar event metadata.
     *
     * @param array $other Candidate event metadata.
     * @return array Safe event metadata.
     */
    private static function safe_other(array $other): array {
        $safe = [];
        foreach ($other as $key => $value) {
            if (!in_array($key, self::SAFE_KEYS, true) || !is_scalar($value)) {
                continue;
            }
            if (is_string($value)) {
                $value = self::mask_secret_markers($value);
            }
            $safe[$key] = $value;
        }
        return $safe;
    }

    /**
     * Remove known secret marker names from event strings.
     *
     * @param string $value Candidate event value.
     * @return string Masked value.
     */
    private static function mask_secret_markers(string $value): string {
        $patterns = [
            '/Api-Authorization-Key/i',
            '/auth\.user/i',
            '/auth\.cred/i',
            '/pasword/i',
            '/raw_payload/i',
        ];
        return preg_replace($patterns, '[MASKED]', $value) ?? '';
    }
}
